[build]
  publish = "public"
  command = "gatsby build"
[build.environment]
  NODE_VERSION = "12.13.0"
  YARN_VERSION = "1.19.1"
  YARN_FLAGS = "--no-ignore-optional"
[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[redirects]]
  from = "/photography/"
  to = "https://celebrated-phoenix-839d0e.netlify.app/"
  status = 200
  force = true # COMMENT: ensure that we always redirect